### ISSUE TITLE
Compile the .bas versions?

### ISSUE THREAD

**Issue by ryanfantus** [Rurik/GWT#1]
Hey there, are you able to compile the QB versions? I can't figure out how to get them to compile but the pascal version craps out and has display issues. Would love to try the game :)

**Comment by Rurik** [comment]
Unfortunately it has been too many years since I have tried to compile or run them, so I wouldn't even know where to start.

**Comment by ryanfantus** [comment]
Do you have binaries or older archives of the games which are already compiled aside from the Pascal one?

**Comment by Rurik** [comment]
Sorry, no. This dates back over 25 years and were reliant on a BBS for some portions. It could possibly be ported to a standalone game that compiles in a more recent language, but as it is, it would require some work to run.

**Comment by ryanfantus** [comment]
Yeah, bummer. I was hoping to run it on my BBS. Oh well, thanks for your response
